### ISSUE TITLE
ENV semantic changed

### ISSUE THREAD

**Issue by troyfolger** [terlar/docker-spotify-pulseaudio#1]
## Dockerfile build error: "Error: ENV must have two arguments"

The Dockerfile as of this writing doesn't build with Docker 1.3, I think the ENV semantic changed. The current Dockerfile uses an '=' to separate the variable and value on the ENV statement ... omitting the '=' fixes it.

I updated the Dockerfile as follows:

    ENV PULSE_SERVER /run/pulse/native

... and re-ran the build command, and the Docker successfully built.

**Comment by terlar** [comment]
I am running Docker 1.4.1, but you are right it should be without the equals, might just be chance that it is working.

**Comment by terlar** [comment]
Updated the Dockerfile. Please let me know if it is working otherwise. I am running it on two machines. Both quite similar though, almost same model of MacBook Retina 13". The newer one that has two soundcards, has a bit of trouble when connecting the headphones to get the sound through.

**Comment by troyfolger** [comment]
Yes, this worked, thank you. I appreciate you publishing this Dockerfile, saved me several hours of doing it myself!

**Comment by troyfolger** [comment]
It looks like things changed in 1.4 to support both semantics: 
http://docs.docker.com/reference/builder/#env

**Comment by terlar** [comment]
Ah, good to know. Better keep it without to be backwards compatible and since we don't set several env anyways, but the other one can be useful to save some layers when setting several.

Great to hear you find it useful, I was hoping for the same, but to my surprise I didn't find any Dockerfile for Spotify. Loads of them for Skype though, so that helped a bit.
