### ISSUE TITLE
docker inspect in version 1.12.1

### ISSUE THREAD

**Issue by PabloCastellano** [terlar/docker-spotify-pulseaudio#8]
I wasn't getting this error in docker 1.7.0

```
$ docker inspect -f "{{ .Name }}" spotify | grep -q '/spotify'
Template parsing error: template: :1:3: executing "" at <.Name>: map has no entry for key "Name"
```

**Comment by terlar** [comment]
Hmm, I am also running 1.12.1 and don't get this error, what about your `containerd` version? Perhaps there could be some issue there.

**Comment by PabloCastellano** [comment]
@terlar Never heard about containerd. So not using it AFAIK. Any other idea?

**Comment by terlar** [comment]
Since docker 1.11 they used containerd as backend as far as I undertand it:

- https://blog.docker.com/2016/04/docker-containerd-integration/
- https://blog.docker.com/2016/04/docker-engine-1-11-runc/

I myself had an issue with `containerd` and installed `docker` version being incompatible. But I am not sure if this is the cause. But to me that error loks very weird and I have not other clue as to why it would not work.

**Comment by terlar** [comment]
You could try to run `docker inspect spotify` to see what data you get back, post it here if there is nothing sensitive in it and we could try to figure out why there is no Name node in that JSON output. Because even if you don't explicitly name stuff it should have a name.
